sudo: required

language: java
jdk:
  - openjdk11

env:
  global:
    - app_name=spring-boot-kotlin-gradle-docker-sample
    - docker_namespace=sairaghavak

services:
  - docker

before_install:
  - chmod +x gradlew

script:
  - ./gradlew clean build
  - cp ./build/libs/*.jar ./docker